::Atlas -d "log\Log1.log" MT2Eng.nes "script\script 1.txt"                >> "log\output.log"
::Atlas -d "log\Log2.log" MT2Eng.nes "script\script 2.txt"                >> "log\output.log"
Atlas -d "log\LogCombat.log" MT2Eng.nes "script\combat.txt"               > "log\output.log"
Atlas -d "log\LogName.log" MT2Eng.nes "script\name screen.txt"            >> "log\output.log"
Atlas -d "log\LogDemons.log" MT2Eng.nes "script\demon names.txt"          >> "log\output.log"
Atlas -d "log\LogRace.log" MT2Eng.nes "script\demon races.txt"            >> "log\output.log"
Atlas -d "log\LogItems.log" MT2Eng.nes "script\item names.txt"            >> "log\output.log"
Atlas -d "log\LogDict.log" MT2Eng.nes "script\item dictionary.txt"        >> "log\output.log"
Atlas -d "log\LogMagic.log" MT2Eng.nes "script\spells.txt"                >> "log\output.log"
Atlas -d "log\LogCommand.log" MT2Eng.nes "script\menu commands.txt"       >> "log\output.log"
Atlas -d "log\LogHealing.log" MT2Eng.nes "script\healing etc.txt"         >> "log\output.log"
Atlas -d "log\LogChoice.log" MT2Eng.nes "script\in dialogue choices.txt"  >> "log\output.log"
Atlas -d "log\LogEnding.log" MT2Eng.nes "script\ending labels.txt"        >> "log\output.log"
Atlas -d "log\LogTown.log" MT2Eng.nes "script\town names.txt"             >> "log\output.log"
Atlas -d "log\LogTeleport.log" MT2Eng.nes "script\teleport locations.txt" >> "log\output.log"
Atlas -d "log\LogAutopilot.log" MT2Eng.nes "script\autopilot areas.txt"   >> "log\output.log"
Atlas -d "log\LogSign.log" MT2Eng.nes "script\dungeon popups.txt"         >> "log\output.log"
Atlas -d "log\LogStatScreen.log" MT2Eng.nes "script\status screen.txt"    >> "log\output.log"
Atlas -d "log\LogTitle.log" MT2Eng.nes "script\title screen.txt"          >> "log\output.log"
Atlas -d "log\LogStatus.log" MT2Eng.nes "script\status.txt"               >> "log\output.log"

::pause