::Atlas -d "log\Log1.log" MT2Eng.nes "script\script 1.txt"               
::Atlas -d "log\Log2.log" MT2Eng.nes "script\script 2.txt"               
Atlas -d "log\LogCombat.log" MT2Eng.nes "script\combat.txt"              
Atlas -d "log\LogName.log" MT2Eng.nes "script\name screen.txt"           
Atlas -d "log\LogDemons.log" MT2Eng.nes "script\demon names.txt"         
Atlas -d "log\LogRace.log" MT2Eng.nes "script\demon races.txt"           
Atlas -d "log\LogItems.log" MT2Eng.nes "script\item names.txt"           
Atlas -d "log\LogDict.log" MT2Eng.nes "script\item dictionary.txt"       
::Atlas -d "log\DTE.log" MT2Eng.nes "script\DTE.txt"
Atlas -d "log\LogMagic.log" MT2Eng.nes "script\spells.txt"               
Atlas -d "log\LogCommand.log" MT2Eng.nes "script\menu commands.txt"      
Atlas -d "log\LogLift.log" MT2Eng.nes "script\elevator choices.txt"      
Atlas -d "log\LogHealing.log" MT2Eng.nes "script\healing etc.txt"        
Atlas -d "log\LogChoice.log" MT2Eng.nes "script\in dialogue choices.txt" 
Atlas -d "log\LogEnding.log" MT2Eng.nes "script\ending labels.txt"       
Atlas -d "log\LogTown.log" MT2Eng.nes "script\town names.txt"            
Atlas -d "log\LogTeleport.log" MT2Eng.nes "script\teleport locations.txt"
Atlas -d "log\LogAutopilot.log" MT2Eng.nes "script\autopilot areas.txt"  
Atlas -d "log\LogSign.log" MT2Eng.nes "script\dungeon popups.txt"        
Atlas -d "log\LogStatScreen.log" MT2Eng.nes "script\status screen.txt"   
Atlas -d "log\LogTitle.log" MT2Eng.nes "script\title screen.txt"         
Atlas -d "log\LogStatus.log" MT2Eng.nes "script\status.txt"              

pause